"use client";

import { motion } from "framer-motion";
import { Scale, BookOpen, AlertCircle, ShieldAlert } from "lucide-react";

export default function TermsPage() {
  return (
    <div className="min-h-screen pt-24 pb-20 px-4 sm:px-6 lg:px-8 max-w-4xl mx-auto">
      <motion.div
        initial={{ opacity: 0, y: 15 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6 }}
      >
        <div className="text-center mb-12">
          <div className="w-16 h-16 bg-primary/10 rounded-2xl mx-auto flex items-center justify-center mb-4 border border-primary/20">
            <Scale className="w-8 h-8 text-primary" />
          </div>
          <h1 className="font-display text-4xl md:text-5xl font-normal text-white mb-4">
            Terms of <span className="italic font-light text-primary">Service</span>
          </h1>
          <p className="text-gray-400">Last updated: May 31, 2026</p>
        </div>

        <div className="glass-panel p-8 sm:p-10 space-y-8 text-gray-300 leading-relaxed font-light">
          <section className="space-y-3">
            <h2 className="text-xl font-bold text-white flex items-center gap-2">
              <BookOpen className="w-5 h-5 text-primary" /> 1. Terms
            </h2>
            <p>
              By accessing the GeoSafe AI platform, you agree to comply with and be bound by these Terms of Service. If you disagree with any part of these terms, you are prohibited from utilizing this platform.
            </p>
          </section>

          <section className="space-y-3 bg-red-500/5 border border-red-500/20 p-6 rounded-xl">
            <h2 className="text-xl font-bold text-red-400 flex items-center gap-2">
              <ShieldAlert className="w-5 h-5 text-red-400" /> 2. AI Disclaimer & Limitations
            </h2>
            <p className="text-gray-200 font-semibold">
              CRITICAL: GeoSafe AI is an informational tool. 
            </p>
            <p className="text-sm">
              All safety assessments, risk parameters, elevation metrics, and compatibility classifications are generated by machine learning models (Random Forest) and open-source geospatial databases (OSM, Natural Earth, NASA SRTM). 
            </p>
            <p className="text-sm">
              These analyses do not constitute professional geological, geotechnical, environmental, or land-surveying advice. Users must secure official surveyor reports, local zoning assessments, and civil engineering verification before engaging in land purchase, commercial transactions, or construction activities.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-bold text-white flex items-center gap-2">
              <AlertCircle className="w-5 h-5 text-primary" /> 3. Use License
            </h2>
            <p>
              GeoSafe AI is distributed under open-source terms. Permission is granted to copy, modify, distribute, and execute the codebase for personal, educational, and commercial uses, subject to the conditions of the open-source licensing specified in our repository.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-bold text-white flex items-center gap-2">
              ⚖️ 4. Limitations of Liability
            </h2>
            <p>
              In no event shall the GeoSafe AI developers, students, or contributors be held liable for any damages (including, without limitation, damages for loss of data, profit, or construction delays) arising out of the use or inability to use the analysis engine, even if notified of the possibility of such damage.
            </p>
          </section>
        </div>
      </motion.div>
    </div>
  );
}
